[package]
name = "arctic-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
tokio = "1.28.2"
tokio-postgres = "0.7"
dotenv = "0.15"
serde_json = "1.0"
serde = "1.0"